<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "int_park"
 *
 * Auto generated by Extension Builder 2019-12-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Interactive Park Planner',
    'description' => 'Interactive Park Planner is a TYPO3 extension which is using leaflet library to place and show markers with its description on an image.',
    'category' => 'plugin',
    'author' => 'Usman Ahmad, Tobias Gräber',
    'author_email' => 'ua@onm.de, tg@onm.de',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-10.99.99',
            "vhs" => ""
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
